### PR TITLE
fix: Input not reformatting after external value changes

### LINKED ISSUE #74: Input not reformatting after value changes
## Description
If a value is changed programmatically the formattedValue doesn't refresh with fractionDigits. The $ is there but not the fractionDigits.

## Version Used

0.11.3

## Expected Behavior

It should show the fractionalDigits

## Actual Behavior

It shows the fractional digits the first time and on a value that is a whole number but if you change to another whole number it doesn't show them.  If you focus in and out of the inputbox it changes like it should.  

## Props Used

List down the props you used with the component, for example:

```svelte
<CurrencyInput name="default" bind:value={formState.AskPrice} />
```

## Reproduction Steps
I took your demo and just added a button click

https://svelte.dev/repl/20a823b0befe40ceb3fd3c4bd0b02bcb?version=4.2.10

1. Click change price in the example 
2. If you leave the number the same it still shows it with the decimal places. As a test, I set askPrice to 22 and change it to 22 it still shows $22.00 
3.

## Additional Info

- OS & Version:
- Browser & Version:
- Any other relevant details or potential solutions:

### PR DESCRIPTION
**Pull request by fmaclen**
Fixes #74

### CODE REVIEW

File: src/lib/CurrencyInput.svelte [hunk 1]
```diff
@@ -78,12 +78,20 @@
...
 
-	// Also set the correct fraction digits when the value is zero on initial load
-	onMount(() => setFormattedValue(true));
+	let dom: Document;
+	let inputElement: HTMLInputElement;
 
-	let inputTarget: HTMLInputElement;
+	onMount(() => {
+		// Set the document object as a variable so we know the page has mounted
+		dom = document;
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:88]: We need the DOM object to check if the user is currently typing on the field.

File: src/lib/CurrencyInput.svelte [hunk 2]
```diff
@@ -78,12 +78,20 @@
...
+
+		// Set the correct fraction digits when the value is zero on initial load
+		setFormattedValue()
+	});
+
+	let inputTarget: EventTarget | null;
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:94]: Used to be:
`let inputTarget: HTMLInputElement;`

But the correct type should have been:
`let inputTarget: EventTarget | null;`

File: src/lib/CurrencyInput.svelte [hunk 3]
```diff
@@ -147,13 +155,16 @@
...
 	};
 
-	const setFormattedValue = (hasMinFractionDigits?: boolean) => {
+	const setFormattedValue = () => {
+		// Do nothing because the page hasn't mounted yet
+		if (!dom) return;
+
 		// Previous caret position
-		const startCaretPosition = inputTarget?.selectionStart || 0;
+		const startCaretPosition = inputElement?.selectionStart || 0;
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:163]: We can get the caret position from `inputElement` now.

File: src/lib/CurrencyInput.svelte [hunk 4]
```diff
@@ -147,13 +155,16 @@
 		}
 	};
 
-	const setFormattedValue = (hasMinFractionDigits?: boolean) => {
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:150]: No longer need to set this boolean variable.

File: src/lib/CurrencyInput.svelte [hunk 5]
```diff
@@ -147,13 +155,16 @@
...
+		if (!dom) return;
+
 		// Previous caret position
-		const startCaretPosition = inputTarget?.selectionStart || 0;
+		const startCaretPosition = inputElement?.selectionStart || 0;
 		const previousFormattedValueLength = formattedValue.length;
 
 		// Apply formatting to input
-		formattedValue = isZero && !isZeroNullish ? '' : formatCurrency(value, fractionDigits, hasMinFractionDigits ? fractionDigits : 0);
+		formattedValue = isZero && !isZeroNullish ? '' : formatCurrency(value, fractionDigits, dom.activeElement == inputElement ? 0 : fractionDigits);
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:167]: If `dom.activeElement == inputElement` is `true` it means the user is typing on it so we don't want to automatically format with fraction digits.

Otherwise, we format with digits because the user clicked out of the input or the value has changed from somewhere else (which fixes the bug described in #74).

File: src/routes/test/+page.svelte [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+		<CurrencyInput name="changed" bind:value={formState.AskPrice} />
+    {/key} -->
+	</div>
+
+	<nav class="demoForm__output">
+		<button type="submit" class="demoForm__submit">Submit form</button>
+	</nav>
+
+	<button on:click={changePrice}>Change Price</button>
+</form>
```
Comment (fmaclen) [inline src/routes/test/+page.svelte:35]: Quick demo before writing a proper test.
Will be deleted.

File: src/lib/CurrencyInput.svelte [hunk 7]
```diff
@@ -147,13 +155,23 @@
...
 
 		// Apply formatting to input
-		formattedValue = isZero && !isZeroNullish ? '' : formatCurrency(value, fractionDigits, hasMinFractionDigits ? fractionDigits : 0);
+		formattedValue =
+			isZero && !isZeroNullish
+				? ''
+				: formatCurrency(
+						value,
+						fractionDigits,
+						dom.activeElement === inputElement ? 0 : fractionDigits
```
Comment (fmaclen) [inline src/lib/CurrencyInput.svelte:173]: If `dom.activeElement == inputElement` is `true` it means the user is typing on it so we don't want to automatically format with fraction digits.

Otherwise, we format with digits because _the user clicked out of the input_ or _the value has changed from somewhere else_ (which fixes the bug described in #74).

File: src/routes/+page.svelte [hunk 8]
```diff
@@ -43,61 +48,105 @@
...
+				fractionDigits={0}
+			/>
+			<button
+				id="set-chained-value"
+				type="button"
+				class="demoForm__button"
+				on:click={setChainedValue}
+			>
+				Set chained value to <strong>420.69</strong>
+			</button>
```
Comment (fmaclen) [inline src/routes/+page.svelte:144]: This button replicates the behavior from #74.
